# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UaSt_waFTpYUTJz3oPbe4noyDKXR5cnU
"""

from flask import Flask, request, abort

from linebot import (
    LineBotApi, WebhookHandler
)
from linebot.exceptions import (
    InvalidSignatureError
)
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage, ImageMessage
)

app = Flask(__name__)

line_bot_api = LineBotApi('w+TeKidP83jbl6Ge5snymt5PFFbdmET+HMdvnRd5BmwsBqaT0tiGm7n1Aj4jZ5TtUAWm4ZUbJlhWpQT6q0+aZj9qcAErOpqXhYx2SbNXH0r4R1paoWmAnW3lhS2Ty+F9GebaNqXgA08iPFzefDEzbQdB04t89/1O/w1cDnyilFU=')
handler = WebhookHandler('8d2ca22db1dbe8d4847d89a9bef047b7')


@app.route("/callback", methods=['POST'])
def callback():
    # get X-Line-Signature header value
    signature = request.headers['X-Line-Signature']

    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)

    # handle webhook body
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        print("Invalid signature. Please check your channel access token/channel secret.")
        abort(400)

    return 'OK'


@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text=event.message.text))

@handler.add(MessageEvent, message=ImageMessage)
def handle_image_message(event):
    # 請line_bot_api抓圖片回來
    image_temp_variable = line_bot_api.get_message_content(event.message.id)

    # 把圖片存成檔案
    with open("./temp/" + event.message.id + '.jpg', 'wb') as f:
        for chunk in image_temp_variable.iter_content():
            f.write(chunk)

    line_bot_api.reply_message(event.reply_token, TextSendMessage("我收到囉"))

if __name__ == "__main__":
    app.run()